function control = parameter__control__create(parameter, context)

% WHITENING - parameter__control__create

% Copyright (C) 2002-2012 Cornell University

%
% This file is part of XBAT.
% 
% XBAT is free software; you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation; either version 2 of the License, or
% (at your option) any later version.
% 
% XBAT is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with XBAT; if not, write to the Free Software
% Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA

control = empty(control_create);

tabs = {'Filter', 'Noise'};

control(end + 1) = control_create( ...
	'style', 'tabs', ...
	'tab', tabs ...
);

control(end + 1) = control_create( ...
	'name', 'order', ...
	'style', 'slider', ...
	'type', 'integer', ...
	'min', 1, ...
	'max', 20, ...
	'tab', tabs{1}, ...
	'value', parameter.order ...
);

control(end + 1) = control_create( ...
	'name', 'r', ...
	'style', 'slider', ...
	'space', 1.5, ...
	'tab', tabs{1}, ...
	'value', parameter.r ...
);

% NOTE: consider allowing use of non-self logs or meta-logs

logs = get_library_logs('info', context.library, context.sound);

state = '__ENABLE__';

if isempty(logs)
	logs = {'(No Logs Found)'}; state = '__DISABLE__';
end

control(end + 1) = control_create( ...
	'name', 'noise_log', ...
	'alias', 'log', ...
	'style', 'popup', ...
	'tab', tabs{2}, ...
	'string', logs, ...
	'value', 1, ...
	'initialstate', state ...
);

control(end + 1) = control_create( ...
	'name', 'use_log', ...
	'alias', 'on', ...
	'style', 'checkbox', ...
	'tab', tabs{2}, ...
	'value', ~isempty(logs) ...
);

