function events = widget_events

events = { ...
	'page', ...
	'timer', ...
	'play__start', ...
	'play__update', ...
	'play__stop', ...
	'selection__create', ...
	'selection__delete', ...
	'selection__edit__start', ...
	'selection__edit__update', ...
	'selection__edit__stop' ...
};
