function control = parameter__control__create(parameter, context)

% WHITEN - parameter__control__create

% Copyright (C) 2002-2012 Cornell University

%
% This file is part of XBAT.
% 
% XBAT is free software; you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation; either version 2 of the License, or
% (at your option) any later version.
% 
% XBAT is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with XBAT; if not, write to the Free Software
% Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA

% NOTE: if we adapt more than once per page we may not use the filter display

fun = parent_fun; control = fun(parameter, context);

control(end + 1) = control_create( ...
	'style', 'separator', ...
	'space', 0.11 ...
);

tabs = {'Filter', 'Noise'};

control(end + 1) = control_create( ...
	'style', 'tabs', ...
	'tab', tabs ...
);

control(end + 1) = control_create( ...
	'name', 'order', ...
	'style', 'slider', ...
	'type', 'integer', ...
	'min', 1, ...
	'max', 512, ...
	'tab', tabs{1}, ...
	'value', parameter.order ...
);

control(end + 1) = control_create( ...
	'name', 'r', ...
	'alias', 'regularize', ...
	'style', 'slider', ...
	'tab', tabs{1}, ...
	'value', parameter.r ...
);

nyq = 0.5 * get_sound_rate(context.sound);

control(end + 1) = control_create( ...
	'name', 'max_freq', ...
	'style', 'slider', ...
	'tab', tabs{1}, ...
	'min', 0, ...
	'max', nyq, ...
	'value', parameter.max_freq ...
);

control(end + 1) = control_create( ...
	'name', 'lowpass', ...
	'alias', 'on', ...
	'style', 'checkbox', ...
	'tab', tabs{1}, ...
	'onload', 1, ...
	'space', 1.25, ...
	'value', parameter.lowpass ...
);

control(end + 1) = control_create( ...
	'name', 'noise_log', ...
	'alias', 'log', ...
	'style', 'popup', ...
	'tab', tabs{2}, ...
	'string', {'names'}, ...
	'value', 1 ...
);

control(end + 1) = control_create( ...
	'name', 'use_log', ...
	'alias', 'on', ...
	'style', 'checkbox', ...
	'onload', 1, ...
	'tab', tabs{2} ...
);
