function control = parameter__control__create(parameter, context)

% RAVEN2XBAT_V2 - parameter__control__create

control = empty(control_create);

control(end + 1) = control_create( ...
	'string','Press OK to run Raven to XBAT converter', ...
	'style','separator', ...
	'type','header', ...
	'space', 0.75 ...
);