function control = parameter__control__create(parameter, context)

% LINEAR_BASE - parameter__control__create

% Copyright (C) 2002-2012 Cornell University

%
% This file is part of XBAT.
% 
% XBAT is free software; you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation; either version 2 of the License, or
% (at your option) any later version.
% 
% XBAT is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with XBAT; if not, write to the Free Software
% Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA

%--
% get nyquist from context
%--

rate = get_sound_rate(context.sound);

nyq = 0.5 * rate;

%--
% filter display
%--

L = {'Frequency', 'Impulse'}; ix = 1;

control(1) = control_create( ...
	'name', 'display', ...
	'style', 'popup', ...
	'label', 0, ...
	'color', get(0, 'defaultuicontrolbackgroundcolor'), ...
	'space', 0.75, ...
	'string', L, ...
	'value', ix ... 
);

% NOTE: onload property should produce display on open

control(end + 1) = control_create( ...
	'name', 'filter', ...
	'style', 'axes', ...
	'onload', 1, ...
	'label', 0, ...
	'lines', 4.5, ...
	'space', 1.5, ...
	'value', parameter.filter ...
);

%--
% filter visualization and selection configuration
%--

control(end).space = 0.25;

if has_toolbox('signal')

	% NOTE: this allows access to the filter visualization tool
	
	control(end + 1) = control_create( ...
		'name', {'fvtool', 'sel_config'}, ...
		'alias', {'FV', char(0)}, ...
		'style', 'buttongroup', ...
		'width', 2/3, ...
		'align', 'right', ...
		'lines', 1.5, ...
		'space', 0.75 ...
	);

else
	
	control(end + 1) = control_create( ...
		'name', 'sel_config', ...
		'alias', char(0), ...
		'style', 'buttongroup', ...
		'width', 1/3, ...
		'align', 'right', ...
		'lines', 1.5, ...
		'space', 0.5 ...
	);
	
end

%--
% collapse panel for specific linear filter controls
%--

% NOTE: this is not working at the moment

% control(end + 1) = section_collapse_control;
