function control = parameter__control__create(parameter, context)

% AMPLITUDE - parameter__control__create

% Copyright (C) 2002-2012 Cornell University

%
% This file is part of XBAT.
% 
% XBAT is free software; you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation; either version 2 of the License, or
% (at your option) any later version.
% 
% XBAT is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with XBAT; if not, write to the Free Software
% Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA

control = empty(control_create);

tabs = {'Block', 'Window'};

control(end + 1) = control_create( ...
	'style', 'tabs', ...
	'tab', tabs ...
);

rate = get_sound_rate(context.sound);

block = get_block_range(rate);

control(end + 1) = control_create( ... 
	'name', 'block', ...
	'alias', 'size', ...
	'style', 'slider', ...
	'tab', tabs{1}, ...
	'min', block(1), ...
	'max', block(2), ...
	'value', parameter.block ...
);

control(end + 1) = control_create( ...
	'name', 'overlap', ...
	'style', 'slider', ...
	'max', 0.95, ...
	'slider_inc', [0.01, 0.1], ...
	'tab', tabs{1}, ...
	'value', parameter.overlap ...
);

control(end + 1) = control_create( ...
	'name', 'auto', ...
	'alias','adapt to page', ...
	'style', 'checkbox', ...
	'tab', tabs{1}, ...
	'space', 1.5, ...
	'value', parameter.auto, ...
	'onload', 1 ...
);
	
